### ISSUE TITLE
代码无法运行

### ISSUE THREAD

**Issue by minshengxinwen** [fitzgerald0/znyy#2]
时间序列聚类算法。
直接下载的完整code，运行ts_shape.py报了以下错误：

Empty DataFrame
Columns: [item_id, qty, date]
Index: []
min time is : nan,max time is : nan
Traceback (most recent call last):
  File "D:\09idm+google\Compressed\time_series_data_mining-master\ts_shape.py", line 154, in <module>
    fin_cluster = main()
  File "D:\09idm+google\Compressed\time_series_data_mining-master\ts_shape.py", line 135, in main
    input_df, multi_id = pcts.read_data()
  File "D:\09idm+google\Compressed\time_series_data_mining-master\ts_shape.py", line 58, in read_data
    data = self.fill_na_ts()
  File "D:\09idm+google\Compressed\time_series_data_mining-master\ts_shape.py", line 39, in fill_na_ts
    time_index = pd.date_range(min_ds, max_ds, freq='D')
  File "C:\Python\Python310\lib\site-packages\pandas\core\indexes\datetimes.py", line 945, in date_range
    dtarr = DatetimeArray._generate_range(
  File "C:\Python\Python310\lib\site-packages\pandas\core\arrays\datetimes.py", line 407, in _generate_range
    raise ValueError("Neither `start` nor `end` can be NaT")
ValueError: Neither `start` nor `end` can be NaT

进程已结束,退出代码1

sale_df.csv 文件内容如下：
date,item_id,qty
,,mean
01.03.2013,30,399.0
01.04.2013,30,399.0
02.03.2013,30,399.0
02.03.2014,30,169.0
03.03.2013,30,399.0
05.03.2013,30,399.0
07.03.2013,30,399.0

不知道,,mean 是什么意思，不管删不删除，程序都无法运行。

**Comment by qiuqqiuu** [comment]
我也是 请问后来解决了吗

**Comment by minshengxinwen** [comment]
> 我也是 请问后来解决了吗

没有，后面不做了
